name: TheFloorIsLava
main: com.rtm516.TheFloorIsLava.TheFloorIsLava
version: 1.3.0
author: rtm516
api-version: 1.14
commands:
   start:
      description: Starts TheFloorIsLava
      usage: /start
permissions:
   thefloorislava.start:
      description: Allows the player to start the game
      default: op