name: TheFloorIsLava
main: com.rtm516.TheFloorIsLava.TheFloorIsLava
version: 0.0.1-SNAPSHOT
author: rtm516
commands:
   start:
      description: Starts TheFloorIsLava
      usage: /start
permissions:
   thefloorislava.start:
      description: Allows the player to start the game
      default: op